### ISSUE TITLE
Missing axis-train weights

### ISSUE THREAD

**Issue by francesco-clementi-92** [AxisCommunications/axis-model-zoo#54]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

I'm following this guide in this repo: https://github.com/AxisCommunications/axis-model-zoo/blob/main/docs/yolov5-on-artpec8.md.

One of the step is:
`We also provide checkpoint weights for yolov5n, yolov5s, and yolov5m, which you can use as a starting point for your training. To use these weights as a starting point, you can use the --weights flag in the train.py command above.`

The reported path for the weights is:
`runs/train/axis-train/weights/best.pt`
`runs/train/axis-train/weights/best-int8.tflite`
However in the YOLO repo there is only `runs/train/exp/weights/best.tflite` with the path exp instead of axis-train

**Comment by Corallo** [comment]
You need to download the weights yourself.
They can be found at the bottom of [the page you linked](https://github.com/AxisCommunications/axis-model-zoo/blob/main/docs/yolov5-on-artpec8.md#6-checkpoints)

**Comment by isak-jakobsson** [comment]
I am closing this issue. If you still need help, reopen it or create a new issue.
